version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - three-tier-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: node-backend

    restart: always

    ports:
      - "5000:5000"

    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      - mysql

    networks:
      - three-tier-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: react-frontend

    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - three-tier-network

volumes:
  mysql-data:

networks:
  three-tier-network:
    driver: bridge